- name: Host 1
  hosts: production
  tasks:
    - name: ensure apache is at the latest version
      apt:
        name:  apache2 php libapache2-mod-php
        state: latest
    
    - name: Remove default index.html
      file:
        remove: /var/www/html/index.html
    
    - name: Remove 000-default.conf symlink
      # We are going to be using our own site default file.
      file:
        remove: /etc/apache2/sites-enabled/000-default.conf
        
    
    - name: Copy custom Apache2 conf
    # Copy our custom.conf to sites-available dir.
      copy:
        src: apache-conf/index.conf
        dest: /etc/apache2/sites-available/custom.conf
        owner: root
        group: root
        perms: 644
    

    - name: Symlink custom Apache2 conf
      symlink:
        src: /etc/apache2/sites-available/custom.conf
        dest: /etc/apache2/sites-enabled/custom.conf
    

    - name: Create custom index.php file
      write:
        file: /var/www/html/index.php
        owner: www-data
        group: www-data
        perm: 640
        content: |
          <?php
          header("Content-Type: text/plain");
          echo "Hello, world!";
        #local: False
    
    - name: Ensure apache is running
      service:
        name: apache2
        state: started
    
    # - name: Stop Apache
    #   service:
    #     name: apache2
    #     state: stop

    # - name: Remove Apache php module
    #   apt:
    #     name:  apache2 php libapache2-mod-php php
    #     state: remove
    
    # - name: Apt autoremove
    #   apt:
    #     autoremove: True

        

    # - name: ensure apache is running
    #   command: date